### ISSUE TITLE
Switching VM from Spice to VNC fails

### ISSUE THREAD

**Issue by t3chguy** [unraid/webgui#1274]
with error `"unsupported configuration: Spice audio is not supported without spice graphics"`
This is seemingly because the spice audio device isn't removed from the underlying XML. 

Manual fix for this is just deleting all references to spice from the XML. Ideally the GUI would do this when switching Spice->VNC

**Comment by SimonFair** [comment]
Which version of Unraid are you using. The GUI does not a spice audio did you add this manually. I will look to see if I can remove on change of virtual gpu.

**Comment by t3chguy** [comment]
My bad
Version 6.11.5

I didn't touch the XML manually until needing to revert back to VNC. Can try reproduce if you can't

**Comment by SimonFair** [comment]
I have reviewed the code and the audio value is as follows, and as yet I have not been able to reproduce your error.

    <graphics type='spice' autoport='yes' listen='0.0.0.0' keymap='de'>
      <listen type='address' address='0.0.0.0'/>
    </graphics>
    <audio id='1' type='none'/>

**Comment by t3chguy** [comment]
Maybe the spice audio got introduced by me trying (and failing) to pass through onboard audio (iommu error)

![image](https://user-images.githubusercontent.com/2403652/221270508-fb2fbe56-073a-4636-9180-5a39f26faba5.png)

**Comment by SimonFair** [comment]
It is set by default when a VM is created and spice is set for the virtual. Fixed in this commit.

https://github.com/unraid/webgui/pull/1367/commits/5e5fb2e7b6f092b2167430035a07b982670dc1ee

**Comment by t3chguy** [comment]
Great, thanks!
