### ISSUE TITLE
[BUG][GUI] UNRAID_7.0.0-beta.2, Buttons suddenly stopped working,  I ran the Update Assistant on tools

### ISSUE THREAD

**Issue by Soliver84** [unraid/webgui#1815]
Hello

the buttons suddenly stopped working, I think it's been since I ran the Update Assistant on tools.
How can I fix it:
![image](https://github.com/user-attachments/assets/c421dfb7-4048-4100-b50b-ec9f00bd94f3)

[tower-diagnostics-20240805-2243.zip](https://github.com/user-attachments/files/16502655/tower-diagnostics-20240805-2243.zip)

**Comment by Soliver84** [comment]
Close Please. Brwoswer Problems

**Comment by ljm42** [comment]
Glad you were able to get past that. Our forums are really the best place to report problems, since you are on a prerelease I'd suggest posting here if you have additional issues or questions: https://forums.unraid.net/bug-reports/prereleases/
