### ISSUE TITLE
Does /etc/rc.d/rc.M run on startup?  Trying to make rsyslog config persist across reboots & upgrades.

### ISSUE THREAD

**Issue by kelvtech-co-uk** [unraid/webgui#1865]
Lines 51-62 in /etc/rc.d/rc.M say that if I create a rsyslog.d directory inside /boot/config then any files here will be symlinked to /etc/rsyslog.d/ and the service restarted.  In my testing however this doesn't happen, what am I getting wrong?  Thanks.

**Comment by ljm42** [comment]
See our forums for info on running Unraid 7.0 betas (based on master): https://forums.unraid.net/bug-reports/prereleases/
