### ISSUE TITLE
7.0.0-rc2 Main view is missing devices and shares

### ISSUE THREAD

**Issue by tomgron** [unraid/webgui#1963]
As shown in the image, there are correct amount of rows in the table, but the contents are empty.

![image](https://github.com/user-attachments/assets/2f6ca220-4cc7-4c49-8d8a-301925fa8a6e)

![image](https://github.com/user-attachments/assets/a0b51a6b-c811-4fdc-bc6b-3b5886049b06)

**Comment by tomgron** [comment]
Actually in the dashboard, most of data is missing too like network, processors and the raid devices

![image](https://github.com/user-attachments/assets/87c37ddc-f527-4f27-bc18-8f5a965cd826)

**Comment by SimonFair** [comment]
Have you tried logging out of the console for about a minute and then logging back in?

If error still shows after than provide results of ps -ef | grep nchan

Suggest logging in prerelease part of the forum.

**Comment by tomgron** [comment]
Actually this thing got sorted after rebooting the server second time.
